- name: Kubernetes의 Event Grid 문서
  href: index.yml
- name: Azure Event Grid 설명서로 전환
  href: ../overview.md
- name: 개요
  items:
    - name: Azure Arc를 사용하는 Kubernetes의 Event Grid는 무엇인가요?
      href: overview.md
    - name: 기능
      href: features.md
- name: 빠른 시작
  items:
    - name: 이벤트 처리기인 웹후크
      href: create-topic-subscription.md
- name: 샘플
  items:
    - name: 코드 샘플
      href: 'https://devblogs.microsoft.com/azure-sdk/event-grid-ga/'
- name: 개념
  items:
    - name: Kubernetes의 Event Grid 개념
      href: concepts.md
    - name: 이벤트 처리기
      href: event-handlers.md
    - name: 이벤트 스키마
      href: event-schemas.md
    - name: 일괄 처리 이벤트 전달
      href: batch-event-delivery.md
    - name: 배달 및 다시 시도
      href: delivery-retry.md
    - name: 이벤트 필터링
      href: filter-events.md
- name: 방법 가이드
  items:
    - name: Event Grid 확장 설치
      href: install-k8s-extension.md
- name: 참조
  items:
    - name: REST API
      href: /rest/api/eventgrid/version2020-10-15-preview/topics
    - name: SDK
      href: ../sdk-overview.md?toc=%2fazure%2fevent-grid%2fkubernetes%2ftoc.json
- name: 리소스
  items:
    - name: 지원 받기
      href: get-support.md
    - name: 약관
      href: legal-terms.md
    - name: Microsoft Q&A
      href: 'https://docs.microsoft.com/answers/topics/azure-event-grid.html'