- name: Docker 설명서
  href: index.yml
- name: 빠른 시작
  expanded: true
  items:
    - name: Docker를 사용하여 Ubuntu VM 배포
      href: 'https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/'
- name: 자습서
  items:
    - name: Docker 및 PostgreSQL을 사용하는 Python 웹앱
      href: ../app-service/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: 'Docker, Jenkins 및 Linux를 사용하는 CI/CD'
      href: /azure/developer/jenkins/pipeline-with-github-and-docker
- name: 방법 가이드
  items:
    - name: Docker VM 확장
      href: 'https://github.com/Azure/azure-docker-extension/blob/master/README.md'
    - name: Docker 컴퓨터
      href: ../virtual-machines/linux/docker-machine.md
    - name: Docker 컨테이너 레지스트리
      href: ../container-registry/container-registry-get-started-portal.md
- name: 리소스
  items:
    - name: Azure 로드맵
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Docker Azure 드라이버
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Docker Azure 사이트
      href: 'https://www.docker.com/docker-azure'
    - name: Docker 사이트
      href: 'https://docker.com'