- name: Kubernetes가 있는 ACS
  href: ./index.yml
- name: 개요
  items:
    - name: 컨테이너 서비스 정보
      href: container-service-intro-kubernetes.md
- name: 빠른 시작
  expanded: true
  items:
    - name: Kubernetes Linux
      href: container-service-kubernetes-walkthrough.md
- name: 자습서
  items:
    - name: 1 - 컨테이너 이미지 만들기
      href: container-service-tutorial-kubernetes-prepare-app.md
    - name: 2 - 컨테이너 레지스트리 만들기
      href: container-service-tutorial-kubernetes-prepare-acr.md
    - name: 3 - Kubernetes 클러스터 만들기
      href: container-service-tutorial-kubernetes-deploy-cluster.md
    - name: 4 - 응용 프로그램 실행
      href: container-service-tutorial-kubernetes-deploy-application.md
    - name: 5 - 응용 프로그램 크기 조정
      href: container-service-tutorial-kubernetes-scale.md
    - name: 6 - 응용 프로그램 업데이트
      href: container-service-tutorial-kubernetes-app-update.md
    - name: 7 - OMS로 모니터링
      href: container-service-tutorial-kubernetes-monitor.md
- name: 샘플
  items:
    - name: Azure CLI
      href: cli-samples.md
- name: 개념
  items:
    - name: 컨테이너 보안
      href: container-service-security.md
    - name: 서비스 사용자 - Kubernetes
      href: container-service-kubernetes-service-principal.md
- name: 방법 가이드
  items:
    - name: Windows를 사용한 Kubernetes 빠른 시작
      href: container-service-kubernetes-windows-walkthrough.md
    - name: 컨테이너 관리 - Kubernetes UI
      href: container-service-kubernetes-ui.md
    - name: Helm 차트 배포
      href: container-service-kubernetes-helm.md
    - name: Kubernetes 및 Jenkins를 사용하는 CI/CD
      href: container-service-kubernetes-jenkins.md
    - name: ACR 및 ACS에서 초안 사용
      href: container-service-draft-up.md
    - name: ACS 클러스터와 연결
      href: container-service-connect.md
    - name: ACS 클러스터 확장
      href: container-service-scale.md
    - name: 모니터
      items:
        - name: Datadog로 모니터링
          href: container-service-kubernetes-datadog.md
        - name: Sysdig로 모니터링
          href: container-service-kubernetes-sysdig.md
        - name: CoScale로 모니터링
          href: container-service-kubernetes-coscale.md
    - name: Spring Boot 앱 배포
      items:
        - name: Azure Container Service에서 Linux에 Spring Boot 응용 프로그램 배포
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Azure Container Service의 Kubernetes 클러스터에 Spring Boot 응용 프로그램 배포
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
- name: 참조
  items:
    - name: Azure CLI 2.0
      href: /cli/azure/acs
    - name: REST (영문)
      href: /rest/api/compute/containerservices
- name: 리소스
  items:
    - name: Azure 로드맵
      href: 'https://azure.microsoft.com/roadmap/'
    - name: FAQ
      href: container-service-faq.md
    - name: 템플릿 - ACS 엔진
      href: 'https://github.com/Azure/acs-engine'
    - name: 가격
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: 지역 가용성
      href: 'https://azure.microsoft.com/regions/services/'
    - name: 스택 오버플로
      href: 'http://stackoverflow.com/questions/tagged/azure-container-service'
    - name: 비디오
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'